CREATE TABLE agricultural_plot (id number(10), name varchar2(255) NOT NULL UNIQUE, area float(10) NOT NULL, watering_systemid number(10), unitid number(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE application_mode (id number(10), application_mode varchar2(255) NOT NULL UNIQUE, PRIMARY KEY (id));
CREATE TABLE building (id number(10), name varchar2(255) NOT NULL, unitid number(10), building_typeid number(10) NOT NULL, dimension double precision, PRIMARY KEY (id));
CREATE TABLE building_type (id number(10), type varchar2(255) NOT NULL UNIQUE, PRIMARY KEY (id));
CREATE TABLE controller (id number(10), watering_systemid number(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE crop (id number(10), name varchar2(255) NOT NULL UNIQUE, crop_typeid number(10) NOT NULL, plantid number(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE crop_plot_registration (cropid number(10) NOT NULL, agricultural_plotid number(10) NOT NULL, amount number(10), unitid number(10), begin_date date NOT NULL, end_date date, PRIMARY KEY (cropid, agricultural_plotid, begin_date));
CREATE TABLE crop_product_registration (cropid number(10) NOT NULL, productid number(10) NOT NULL, PRIMARY KEY (cropid, productid));
CREATE TABLE crop_type (id number(10), type varchar2(255) NOT NULL UNIQUE, PRIMARY KEY (id));
CREATE TABLE datasheet_item (datasheet_itemid number(10) NOT NULL, substanceid number(10) NOT NULL, amount double precision NOT NULL, production_factorid number(10) NOT NULL, PRIMARY KEY (datasheet_itemid, substanceid));
CREATE TABLE distribution_type (id number(10), type varchar2(255) NOT NULL UNIQUE, PRIMARY KEY (id));
CREATE TABLE fertilization (operationid number(10) NOT NULL, production_factorid number(10) NOT NULL, area float(10), unitid number(10), agricultural_plotid number(10) NOT NULL, PRIMARY KEY (operationid));
CREATE TABLE fertilization_with_crop (operationid number(10) NOT NULL, cropid number(10) NOT NULL, PRIMARY KEY (operationid));
CREATE TABLE format (id number(10), format varchar2(255) NOT NULL UNIQUE, PRIMARY KEY (id));
CREATE TABLE harvest (operationid number(10) NOT NULL, productid number(10) NOT NULL, agricultural_plotid number(10) NOT NULL, PRIMARY KEY (operationid));
CREATE TABLE log_type (id number(10), type varchar2(255) NOT NULL UNIQUE, PRIMARY KEY (id));
CREATE TABLE manufacturer (id number(10), manufacturer varchar2(255) NOT NULL UNIQUE, PRIMARY KEY (id));
CREATE TABLE operation (id number(10), operation_date date NOT NULL, amount float(10), unitid number(10), status number(1) NOT NULL, created_at timestamp(0) DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY (id));
CREATE TABLE operation_type (id number(10), type varchar2(255) NOT NULL UNIQUE, PRIMARY KEY (id));
CREATE TABLE operations_log (id number(10), operationid number(10) NOT NULL, log_typeid number(10) NOT NULL, operation_typeid number(10) NOT NULL, "date" timestamp(0) NOT NULL, PRIMARY KEY (id));
CREATE TABLE phytopharmaco_application (operationid number(10) NOT NULL, cropid number(10), wateringid number(10), recipeid number(10) NOT NULL, agricultural_plotid number(10), PRIMARY KEY (operationid));
CREATE TABLE plant (id number(10), specie varchar2(255) NOT NULL, plant_nameid number(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE plant_name (id number(10), common_name varchar2(255) NOT NULL, variety varchar2(255) NOT NULL, PRIMARY KEY (id));
CREATE TABLE plantation (operationid number(10) NOT NULL, cropid number(10) NOT NULL, agricultural_plotid number(10) NOT NULL, compass float(10), distance_between_rows float(10), area float(10), PRIMARY KEY (operationid));
CREATE TABLE product (id number(10), name varchar2(255) NOT NULL, PRIMARY KEY (id));
CREATE TABLE production_factor (id number(10), commercial_name varchar2(255) NOT NULL, application_modeid number(10) NOT NULL, formatid number(10) NOT NULL, manufacturerid number(10) NOT NULL, production_factor_typeid number(10) NOT NULL, acidity_degree float(10), density number(10), PRIMARY KEY (id));
CREATE TABLE production_factor_recipe (production_factorid number(10) NOT NULL, recipeid number(10) NOT NULL, amount float(10) NOT NULL, unitid number(10) NOT NULL, PRIMARY KEY (production_factorid, recipeid));
CREATE TABLE production_factor_type (id number(10), type varchar2(255) NOT NULL UNIQUE, PRIMARY KEY (id));
CREATE TABLE pruning (operationid number(10) NOT NULL, cropid number(10) NOT NULL, agricultural_plotid number(10) NOT NULL, PRIMARY KEY (operationid));
CREATE TABLE recipe (id number(10), name varchar2(255) NOT NULL, PRIMARY KEY (id));
CREATE TABLE sector (id number(10), name varchar2(255) NOT NULL UNIQUE, flow number(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE sector_crop_plot_registration (sectorid number(10) NOT NULL, cropid number(10) NOT NULL, agricultural_plotid number(10) NOT NULL, crop_agricultural_plotbegin_date date NOT NULL, begin_date date NOT NULL, end_date date, begin_date_crop date NOT NULL, end_date_crop date, PRIMARY KEY (sectorid, cropid, agricultural_plotid, crop_agricultural_plotbegin_date));
CREATE TABLE seeding (operationid number(10) NOT NULL, area float(10), unitid number(10), cropid number(10) NOT NULL, agricultural_plotid number(10) NOT NULL, PRIMARY KEY (operationid));
CREATE TABLE sensor (id number(10), sensor_typeid number(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE sensor_agricultural_plot (sensorid number(10) NOT NULL, agricultural_plotid number(10) NOT NULL, PRIMARY KEY (sensorid, agricultural_plotid));
CREATE TABLE sensor_data (id number(10), value double precision NOT NULL, "date" date NOT NULL, sensorid number(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE sensor_type (id number(10), type varchar2(255) NOT NULL UNIQUE, PRIMARY KEY (id));
CREATE TABLE soil_incorporation (operationid number(10) NOT NULL, agricultural_plotid number(10) NOT NULL, PRIMARY KEY (operationid));
CREATE TABLE substance (id number(10), chemical_formula varchar2(255) NOT NULL, PRIMARY KEY (id));
CREATE TABLE unit (id number(10), unit varchar2(255) NOT NULL UNIQUE, PRIMARY KEY (id));
CREATE TABLE watering (operationid number(10) NOT NULL, sectorid number(10), time varchar2(255), PRIMARY KEY (operationid));
CREATE TABLE watering_plan (id number(10), watering_order number(10) NOT NULL, watering_systemid number(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE watering_system (id number(10), dimension number(10) NOT NULL, watering_typeid number(10) NOT NULL, distribution_typeid number(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE watering_type (id number(10), type varchar2(255) NOT NULL UNIQUE, PRIMARY KEY (id));
CREATE TABLE watering_with_crop (operationid number(10) NOT NULL, cropid number(10) NOT NULL, agricultural_plotid number(10) NOT NULL, PRIMARY KEY (operationid));
CREATE TABLE weed (operationid number(10) NOT NULL, weed_typeid number(10), agricultural_plotid number(10) NOT NULL, PRIMARY KEY (operationid));
CREATE TABLE weed_type (id number(10), weed_type varchar2(255) NOT NULL UNIQUE, PRIMARY KEY (id));
CREATE TABLE weed_with_crop (operationid number(10) NOT NULL, cropid number(10) NOT NULL, PRIMARY KEY (operationid));
ALTER TABLE crop_plot_registration ADD CONSTRAINT FKcrop_plot_647404 FOREIGN KEY (cropid) REFERENCES crop (id);
ALTER TABLE controller ADD CONSTRAINT FKcontroller820172 FOREIGN KEY (watering_systemid) REFERENCES watering_system (id);
ALTER TABLE watering_plan ADD CONSTRAINT FKwatering_p52776 FOREIGN KEY (watering_systemid) REFERENCES watering_system (id);
ALTER TABLE sensor_data ADD CONSTRAINT FKsensor_dat593620 FOREIGN KEY (sensorid) REFERENCES sensor (id);
ALTER TABLE crop ADD CONSTRAINT FKcrop67236 FOREIGN KEY (plantid) REFERENCES plant (id);
ALTER TABLE datasheet_item ADD CONSTRAINT FKdatasheet_109858 FOREIGN KEY (substanceid) REFERENCES substance (id);
ALTER TABLE agricultural_plot ADD CONSTRAINT FKagricultur994350 FOREIGN KEY (watering_systemid) REFERENCES watering_system (id);
ALTER TABLE sensor_agricultural_plot ADD CONSTRAINT FKsensor_agr448871 FOREIGN KEY (sensorid) REFERENCES sensor (id);
ALTER TABLE sensor_agricultural_plot ADD CONSTRAINT FKsensor_agr148907 FOREIGN KEY (agricultural_plotid) REFERENCES agricultural_plot (id);
ALTER TABLE datasheet_item ADD CONSTRAINT FKdatasheet_900394 FOREIGN KEY (production_factorid) REFERENCES production_factor (id);
ALTER TABLE fertilization ADD CONSTRAINT FKfertilizat578940 FOREIGN KEY (production_factorid) REFERENCES production_factor (id);
ALTER TABLE fertilization ADD CONSTRAINT FKfertilizat893337 FOREIGN KEY (operationid) REFERENCES operation (id);
ALTER TABLE soil_incorporation ADD CONSTRAINT FKsoil_incor970535 FOREIGN KEY (operationid) REFERENCES operation (id);
ALTER TABLE watering ADD CONSTRAINT FKwatering256564 FOREIGN KEY (operationid) REFERENCES operation (id);
ALTER TABLE pruning ADD CONSTRAINT FKpruning766715 FOREIGN KEY (operationid) REFERENCES operation (id);
ALTER TABLE seeding ADD CONSTRAINT FKseeding944765 FOREIGN KEY (operationid) REFERENCES operation (id);
ALTER TABLE plantation ADD CONSTRAINT FKplantation628446 FOREIGN KEY (operationid) REFERENCES operation (id);
ALTER TABLE harvest ADD CONSTRAINT FKharvest273627 FOREIGN KEY (productid) REFERENCES product (id);
ALTER TABLE harvest ADD CONSTRAINT FKharvest530208 FOREIGN KEY (operationid) REFERENCES operation (id);
ALTER TABLE plant ADD CONSTRAINT FKplant531505 FOREIGN KEY (plant_nameid) REFERENCES plant_name (id);
ALTER TABLE sensor ADD CONSTRAINT FKsensor51961 FOREIGN KEY (sensor_typeid) REFERENCES sensor_type (id);
ALTER TABLE crop ADD CONSTRAINT FKcrop230011 FOREIGN KEY (crop_typeid) REFERENCES crop_type (id);
ALTER TABLE production_factor ADD CONSTRAINT FKproduction947709 FOREIGN KEY (application_modeid) REFERENCES application_mode (id);
ALTER TABLE production_factor ADD CONSTRAINT FKproduction102454 FOREIGN KEY (formatid) REFERENCES format (id);
ALTER TABLE production_factor ADD CONSTRAINT FKproduction243287 FOREIGN KEY (manufacturerid) REFERENCES manufacturer (id);
ALTER TABLE production_factor ADD CONSTRAINT FKproduction634886 FOREIGN KEY (production_factor_typeid) REFERENCES production_factor_type (id);
ALTER TABLE watering_system ADD CONSTRAINT FKwatering_s456526 FOREIGN KEY (watering_typeid) REFERENCES watering_type (id);
ALTER TABLE watering_system ADD CONSTRAINT FKwatering_s154907 FOREIGN KEY (distribution_typeid) REFERENCES distribution_type (id);
ALTER TABLE building ADD CONSTRAINT FKbuilding259524 FOREIGN KEY (building_typeid) REFERENCES building_type (id);
ALTER TABLE operation ADD CONSTRAINT FKoperation775326 FOREIGN KEY (unitid) REFERENCES unit (id);
ALTER TABLE building ADD CONSTRAINT FKbuilding394781 FOREIGN KEY (unitid) REFERENCES unit (id);
ALTER TABLE agricultural_plot ADD CONSTRAINT FKagricultur674191 FOREIGN KEY (unitid) REFERENCES unit (id);
ALTER TABLE phytopharmaco_application ADD CONSTRAINT FKphytopharm747773 FOREIGN KEY (operationid) REFERENCES operation (id);
ALTER TABLE sector_crop_plot_registration ADD CONSTRAINT FKsector_cro614684 FOREIGN KEY (sectorid) REFERENCES sector (id);
ALTER TABLE crop_plot_registration ADD CONSTRAINT FKcrop_plot_658948 FOREIGN KEY (unitid) REFERENCES unit (id);
ALTER TABLE watering ADD CONSTRAINT FKwatering148474 FOREIGN KEY (sectorid) REFERENCES sector (id);
ALTER TABLE seeding ADD CONSTRAINT FKseeding684285 FOREIGN KEY (unitid) REFERENCES unit (id);
ALTER TABLE sector_crop_plot_registration ADD CONSTRAINT FKsector_cro345238 FOREIGN KEY (cropid, agricultural_plotid, crop_agricultural_plotbegin_date) REFERENCES crop_plot_registration (cropid, agricultural_plotid, begin_date);
ALTER TABLE crop_plot_registration ADD CONSTRAINT FKcrop_plot_156546 FOREIGN KEY (agricultural_plotid) REFERENCES agricultural_plot (id);
ALTER TABLE phytopharmaco_application ADD CONSTRAINT FKphytopharm583221 FOREIGN KEY (cropid) REFERENCES crop (id);
ALTER TABLE pruning ADD CONSTRAINT FKpruning564279 FOREIGN KEY (cropid) REFERENCES crop (id);
ALTER TABLE seeding ADD CONSTRAINT FKseeding695829 FOREIGN KEY (cropid) REFERENCES crop (id);
ALTER TABLE plantation ADD CONSTRAINT FKplantation987850 FOREIGN KEY (cropid) REFERENCES crop (id);
ALTER TABLE production_factor_recipe ADD CONSTRAINT FKproduction411797 FOREIGN KEY (production_factorid) REFERENCES production_factor (id);
ALTER TABLE production_factor_recipe ADD CONSTRAINT FKproduction909184 FOREIGN KEY (recipeid) REFERENCES recipe (id);
ALTER TABLE production_factor_recipe ADD CONSTRAINT FKproduction726451 FOREIGN KEY (unitid) REFERENCES unit (id);
ALTER TABLE operations_log ADD CONSTRAINT FKoperations281838 FOREIGN KEY (operationid) REFERENCES operation (id);
ALTER TABLE crop_product_registration ADD CONSTRAINT FKcrop_produ997339 FOREIGN KEY (cropid) REFERENCES crop (id);
ALTER TABLE crop_product_registration ADD CONSTRAINT FKcrop_produ381354 FOREIGN KEY (productid) REFERENCES product (id);
ALTER TABLE weed ADD CONSTRAINT FKweed174312 FOREIGN KEY (weed_typeid) REFERENCES weed_type (id);
ALTER TABLE weed ADD CONSTRAINT FKweed58677 FOREIGN KEY (operationid) REFERENCES operation (id);
ALTER TABLE weed_with_crop ADD CONSTRAINT FKweed_with_434923 FOREIGN KEY (operationid) REFERENCES weed (operationid);
ALTER TABLE weed_with_crop ADD CONSTRAINT FKweed_with_538811 FOREIGN KEY (cropid) REFERENCES crop (id);
ALTER TABLE fertilization ADD CONSTRAINT FKfertilizat735713 FOREIGN KEY (unitid) REFERENCES unit (id);
ALTER TABLE fertilization_with_crop ADD CONSTRAINT FKfertilizat625745 FOREIGN KEY (operationid) REFERENCES fertilization (operationid);
ALTER TABLE fertilization_with_crop ADD CONSTRAINT FKfertilizat352534 FOREIGN KEY (cropid) REFERENCES crop (id);
ALTER TABLE watering_with_crop ADD CONSTRAINT FKwatering_w146145 FOREIGN KEY (operationid) REFERENCES watering (operationid);
ALTER TABLE watering_with_crop ADD CONSTRAINT FKwatering_w483939 FOREIGN KEY (cropid) REFERENCES crop (id);
ALTER TABLE phytopharmaco_application ADD CONSTRAINT FKphytopharm155651 FOREIGN KEY (wateringid) REFERENCES watering (operationid);
ALTER TABLE phytopharmaco_application ADD CONSTRAINT FKphytopharm412032 FOREIGN KEY (recipeid) REFERENCES recipe (id);
ALTER TABLE operations_log ADD CONSTRAINT FKoperations464709 FOREIGN KEY (log_typeid) REFERENCES log_type (id);
ALTER TABLE operations_log ADD CONSTRAINT FKoperations341645 FOREIGN KEY (operation_typeid) REFERENCES operation_type (id);
ALTER TABLE harvest ADD CONSTRAINT FKharvest398754 FOREIGN KEY (agricultural_plotid) REFERENCES agricultural_plot (id);
ALTER TABLE pruning ADD CONSTRAINT FKpruning73421 FOREIGN KEY (agricultural_plotid) REFERENCES agricultural_plot (id);
ALTER TABLE soil_incorporation ADD CONSTRAINT FKsoil_incor160918 FOREIGN KEY (agricultural_plotid) REFERENCES agricultural_plot (id);
ALTER TABLE seeding ADD CONSTRAINT FKseeding186688 FOREIGN KEY (agricultural_plotid) REFERENCES agricultural_plot (id);
ALTER TABLE plantation ADD CONSTRAINT FKplantation503007 FOREIGN KEY (agricultural_plotid) REFERENCES agricultural_plot (id);
ALTER TABLE fertilization ADD CONSTRAINT FKfertilizat238116 FOREIGN KEY (agricultural_plotid) REFERENCES agricultural_plot (id);
ALTER TABLE watering_with_crop ADD CONSTRAINT FKwatering_w993080 FOREIGN KEY (agricultural_plotid) REFERENCES agricultural_plot (id);
ALTER TABLE phytopharmaco_application ADD CONSTRAINT FKphytopharm92363 FOREIGN KEY (agricultural_plotid) REFERENCES agricultural_plot (id);
ALTER TABLE weed ADD CONSTRAINT FKweed781459 FOREIGN KEY (agricultural_plotid) REFERENCES agricultural_plot (id);
